### ISSUE TITLE
请停止在项目简介贬低他人项目的行为

### ISSUE THREAD

**Issue by TheZihanGu** [JVAV-Lang/Jvav#1]
我是 [TZG-Official/Jvav](https://github.com/TZG-official/Jvav) 项目的所有者。   
在此想跟贵项目讨论一下关于项目简介的问题。   
![Screenshot-2020-04-23下午12 00 43](https://user-images.githubusercontent.com/39030261/80059599-f7db8400-855e-11ea-99fb-e6145c7c3182.png)
此图片是本人于 2020 年 4 月 23 日 12:00 分(UTC +8) 截图的，内容为 GitHub 搜索 Jvav 关键字后出现的结果列表。   
从截图中可以清楚的看到，本人的项目位于搜索列表中的第一位，而贵项目位于第二位。   
但是贵项目的简介「楼上的交互解释器不靠谱，这里才是真JVAV」让我感到十分疑惑。Jvav 是一个梗，并非真实存在的编程语言。那么又有什么真假呢。   
我又反复查看了你们的项目 README.md 和网站，明白了原因。但是在没有被更多人认可的时候，贸然声称自己的项目是一个真正的编程语言，还称其他的项目是「假的」，这是否有点不大合适呢。   
并且我也需要再声明一点，我的项目不包含 Jvav 的解释器，仅包含了 Jvav.top 的网站内容开发。此解释器是由 [30266-Official](https://github.com/30266-Official) 编写的，我只是采用了这个罢了。那么您就算真的想来贬低我的项目，那么是不是也要先看清楚贬低对象的项目内容呢。   
目前我也不想做什么事情。只是想请贵项目删除项目简介中贬低他人项目的内容。   
当然，贵项目不做也可以。我也不会采取同样的手段进行「回击」，我也会认为贵项目的行为真的「可笑至极」。

**Comment by Lampese** [comment]
这里是目前我账号的登录状态

我只在前十二小时的时候更新过几次wiki和readme
昨晚在别的群发过自己的账号，遂被盗，目前若是否有什么可以解决问题的办法？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheZihanGu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 中午12:44
收件人:&nbsp;"JVAV-Lang/Jvav"<Jvav@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JVAV-Lang/Jvav] 请停止在项目简介贬低他人项目的行为 (#1)





 
我是 TZG-Official/Jvav 项目的所有者。
 在此想跟贵项目讨论一下关于项目简介的问题。
 
 此图片是本人于 2020 年 4 月 23 日 12:00 分(UTC +8) 截图的，内容为 GitHub 搜索 Jvav 关键字后出现的结果列表。
 从截图中可以清楚的看到，本人的项目位于搜索列表中的第一位，而贵项目位于第二位。
 但是贵项目的简介「楼上的交互解释器不靠谱，这里才是真JVAV」让我感到十分疑惑。Jvav 是一个梗，并非真实存在的编程语言。那么又有什么真假呢。
 我又反复查看了你们的项目 README.md 和网站，明白了原因。但是在没有被更多人认可的时候，贸然声称自己的项目是一个真正的编程语言，还称其他的项目是「假的」，这是否有点不大合适呢。
 并且我也需要再声明一点，我的项目不包含 Jvav 的解释器，仅包含了 Jvav.top 的网站内容开发。此解释器是由 30266-Official 编写的，我只是采用了这个罢了。那么您就算真的想来贬低我的项目，那么是不是也要先看清楚贬低对象的项目内容呢。
 目前我也不想做什么事情。只是想请贵项目删除项目简介中贬低他人项目的内容。
 当然，贵项目不做也可以。我也不会采取同样的手段进行「回击」，我也会认为贵项目的行为真的「可笑至极」。

**Comment by Lampese** [comment]
第三封顺带:
我因为账号被盗致以歉意
目前我很多存储库都被恶意修改了
私密的存储库也有被删除，现在这个邮箱也只能发邮件找不回github密码
不清楚如何是好
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheZihanGu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 中午12:44
收件人:&nbsp;"JVAV-Lang/Jvav"<Jvav@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JVAV-Lang/Jvav] 请停止在项目简介贬低他人项目的行为 (#1)





 
我是 TZG-Official/Jvav 项目的所有者。
 在此想跟贵项目讨论一下关于项目简介的问题。
 
 此图片是本人于 2020 年 4 月 23 日 12:00 分(UTC +8) 截图的，内容为 GitHub 搜索 Jvav 关键字后出现的结果列表。
 从截图中可以清楚的看到，本人的项目位于搜索列表中的第一位，而贵项目位于第二位。
 但是贵项目的简介「楼上的交互解释器不靠谱，这里才是真JVAV」让我感到十分疑惑。Jvav 是一个梗，并非真实存在的编程语言。那么又有什么真假呢。
 我又反复查看了你们的项目 README.md 和网站，明白了原因。但是在没有被更多人认可的时候，贸然声称自己的项目是一个真正的编程语言，还称其他的项目是「假的」，这是否有点不大合适呢。
 并且我也需要再声明一点，我的项目不包含 Jvav 的解释器，仅包含了 Jvav.top 的网站内容开发。此解释器是由 30266-Official 编写的，我只是采用了这个罢了。那么您就算真的想来贬低我的项目，那么是不是也要先看清楚贬低对象的项目内容呢。
 目前我也不想做什么事情。只是想请贵项目删除项目简介中贬低他人项目的内容。
 当然，贵项目不做也可以。我也不会采取同样的手段进行「回击」，我也会认为贵项目的行为真的「可笑至极」。

**Comment by Lampese** [comment]
您好,我是Jvav-Lang/Jvav库的开发者Lampese
前几封邮件我有些急切，现在我平静下来写下这些内容
首先，我不会在得不到认可的时候攻击他人的项目
我的账号从2020.4.22开始被盗了，邮箱呢，我也只能用来进行回复，应该是还没被刷掉，但是不能进行修改密码的操作，具体也可以看提交记录，盗取我账号的人删除了我的几个非常重要的文件。
同时我的几个重要的存储库也被删除，比如我一直在开发的AirAl作品，OM等等。
Jvav项目本来也就是我们的一个梗，我也没怎么说过他是一个语言，我的账号密码被认识的人透露在了一个交流群，遂我账号被盗，我非常尊敬贵项目，也没有对贵项目的任何的攻击的意思，现在我的账号被盗的情况下我也不清楚应该如何解决这一件事、
我不知道他们为什么要修改我的这些存储库，进行一些引战的言论，因为在你说了这件事之后我知道了不止一件事情。
我的账号不仅被盗，盗号者还对我的存储库进行了恶意修改，我希望可以通过友好的途径解决这个问题，因为我也不清楚我的账号接下来会被怎么样，或者盗号者会不会看到这条动态。
此致。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TheZihanGu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年4月23日(星期四) 中午12:44
收件人:&nbsp;"JVAV-Lang/Jvav"<Jvav@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[JVAV-Lang/Jvav] 请停止在项目简介贬低他人项目的行为 (#1)





 
我是 TZG-Official/Jvav 项目的所有者。
 在此想跟贵项目讨论一下关于项目简介的问题。
 
 此图片是本人于 2020 年 4 月 23 日 12:00 分(UTC +8) 截图的，内容为 GitHub 搜索 Jvav 关键字后出现的结果列表。
 从截图中可以清楚的看到，本人的项目位于搜索列表中的第一位，而贵项目位于第二位。
 但是贵项目的简介「楼上的交互解释器不靠谱，这里才是真JVAV」让我感到十分疑惑。Jvav 是一个梗，并非真实存在的编程语言。那么又有什么真假呢。
 我又反复查看了你们的项目 README.md 和网站，明白了原因。但是在没有被更多人认可的时候，贸然声称自己的项目是一个真正的编程语言，还称其他的项目是「假的」，这是否有点不大合适呢。
 并且我也需要再声明一点，我的项目不包含 Jvav 的解释器，仅包含了 Jvav.top 的网站内容开发。此解释器是由 30266-Official 编写的，我只是采用了这个罢了。那么您就算真的想来贬低我的项目，那么是不是也要先看清楚贬低对象的项目内容呢。
 目前我也不想做什么事情。只是想请贵项目删除项目简介中贬低他人项目的内容。
 当然，贵项目不做也可以。我也不会采取同样的手段进行「回击」，我也会认为贵项目的行为真的「可笑至极」。

**Comment by KooriMoe** [comment]
由于某些原因，能否请您删除这个 Issue?
十分感谢。
