### ISSUE TITLE
我想用您的jvav灵感和部分内容

### ISSUE THREAD

**Issue by Hymomo** [JVAV-Lang/Jvav#6]
我也在做关于jvav的内容(虽然这个语言是虚构的)，而且我想让这个语言变得更简洁，因此需要许多人的意见，而我看到了您的jvav文件，浏览了且感觉比我做的好多了，因此想用使用您的部分代码和灵感，我也是一时兴起才想要写的，先声明，我是纯Python/C++小白，很多语法都不是很会，所以可能制作的会有很多错误，我会在内容中表明原作者，希望能够理解!

**Comment by Lampese** [comment]
这是我初二的时候用半吊的代码水平写的一个玩具吧，码风我目前的评价是相当烂，不过是一个玩具就没太关心。

如果你希望参考/借鉴/使用部分代码的话请随意。
